# Generated by Django 3.0.2 on 2020-01-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('capital_city', models.CharField(max_length=100)),
                ('flag_img', models.URLField()),
                ('continent', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
