# Generated by Django 3.0.2 on 2020-01-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_president'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='president',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterField(
            model_name='president',
            name='end_date',
            field=models.DateField(verbose_name='Presidency End'),
        ),
        migrations.AlterField(
            model_name='president',
            name='start_date',
            field=models.DateField(verbose_name='Presidency Start'),
        ),
    ]
