# Generated by Django 2.2.9 on 2020-02-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0004_flag_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='flag',
            name='languages',
            field=models.ManyToManyField(to='flags.Language'),
        ),
    ]
